### ISSUE TITLE
Using `Section` outside of `Morphology` scope 

### ISSUE THREAD

**Issue by arsenius7** [BlueBrain/MorphIO#29] opened 2018-12-14 07:55 UTC
In some usecases, we are interested only in loading and transforming a single neurite from a given Morphology.

A natural flow would be some like
```
def load_axon(filepath):
    morph = morphio.Morphology(filepath)
    result = morph.root_sections[0]  # for the sake of brevity, let's assume it's axon
    return result

axon = load_axon('blah')
for s in axon.iter():
    ...
```

It seems though that once `morph` object goes out of scope, `axon` is invalidated.
I vaguely remember we saw something like that before.
Is there a mechanism to hold morphology memory representation from `Section`?

Alternatively, what would work for this particular usecase is loading _only_ axon in the morphology object.
In this case I can operate the whole morphology object (pass it around, transform points, etc.) without caring to extract the neurite of interest.

More radical proposal: sacrifice "view into C++ object memory" paradigm in Python; and make a copy of internal data into Python world on morphology loading. At the cost of data copy, we'll save ourselves from _tons_ of headaches (see also #28, for instance). Getting memory management right in both C++ and Python with the same code can be very tricky.

Tested with 2.0.0 wheel as I could not install dev version of BB5 (see also #26).

**Comment by mgeplf** [comment] 2020-03-02 14:07
Does that bug repro still work?

**Comment by wizmer** [comment] 2020-03-02 14:13
Yes.
```
Traceback (most recent call last):
  File "/home/bcoste/.virtualenvs/io/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/bcoste/workspace/io/tests/test_5_mut.py", line 411, in test_python_ownership
    assert_equal(len(new_axon2.children), 2)
AssertionError: 0 != 2
```
with MorphIO v2.3.5

**Comment by mgeplf** [comment] 2020-03-03 10:30
Turns out the above report was for `morphio.mut.Morphology`, but the original bug report was for the non-mut version (`morphio.Morphology`).  I have spent a bunch of time trying to reproduce it for the immutable version, and I can't, so I don't think this is a problem any more - hence we can close it.

**Closed by mgeplf** 2020-03-03 10:30 UTC
Labels: bug, python
