### ISSUE TITLE
`os.exec` will hang with Mpi after importing morphio

### ISSUE THREAD

**Issue by ferdonline** [BlueBrain/MorphIO#316] opened 2021-05-17 18:09 UTC
This is a convoluted problem, but seems to be on morphio.

The following python program will hang forever if launched with hpe-mpi
```python
import os
import morphio
os.execlp("printf", "%s", "Hello World!\n")
```

Such problem doesn't happen with  even large Python code bases, with dozens of imports... but only if we import morphio it will hang.

**Comment by mgeplf** [comment] 2021-05-18 06:22
How was morphio installed?

**Comment by mgeplf** [comment] 2021-05-21 07:55
@ferdonline any update on this?

**Comment by pramodk** [comment] 2021-05-28 06:56
@ferdonline @jorblancoa: this could be our good free-friday ticket  😃 . @jorblancoa has looked into similar issues into NEURON and I think we should be able to find the root cause.

**Comment by mgeplf** [comment] 2021-05-28 07:08
I just looked at this; it does indeed seem to be how it's being compiled.

A fresh MorphIO install from the _wheels_ works no problem:
```
$ srun python -c "import os, morphio; os.execv('/bin/ls', ('-al',))"
```

But using the spack built one:
```
$ module load unstable py-neurodamus
$ srun python -c "import os, morphio; os.execv('/bin/ls', ('-al',))"
```

Hangs.

```
$ spack spec py-neurodamus

Input spec
--------------------------------
py-neurodamus

Concretized
--------------------------------
py-neurodamus@2.6.0%gcc@9.3.0 arch=linux-rhel7-x86_64
[snip]
    ^py-h5py@3.1.0%gcc@9.3.0+mpi arch=linux-rhel7-x86_64
        ^hdf5@1.10.7%gcc@9.3.0+cxx~debug~fortran+hl~java+mpi+pic+shared~szip~threadsafe api=none arch=linux-rhel7-x86_64
            ^hpe-mpi@2.22.hmpt%gcc@9.3.0 arch=linux-rhel7-x86_64
[snip]
```
I would hasard a guess that this is related to the MPI inclusion for hdf5.

**Comment by mgeplf** [comment] 2021-07-01 07:12
@ferdonline / @pramodk / @jorblancoa any update on this? I need feedback to be able to diagnose the problem more accurately.

**Comment by mgeplf** [comment] 2021-08-30 09:52
@ferdonline / @pramodk / @jorblancoa any update on this?

**Comment by pramodk** [comment] 2021-08-30 10:20
As people are now gradually coming back from summer break, we will  follow on this issue. (cc: @sergiorg-hpc)

**Comment by mgeplf** [comment] 2021-09-20 07:56
@ferdonline / @pramodk / @jorblancoa any update on this?

**Comment by sergiorg-hpc** [comment] 2021-09-21 08:16
@mgeplf Sorry for the delay! I actually started looking at this issue a couple of weeks ago, but I needed to step away for a bit due to the Disaster Recovery effort. I haven't forget the other ticket we discussed a few weeks back as well.

I will try to take a look with my colleague @jorblancoa between end of this week and next week, ok?

**Comment by sergiorg-hpc** [comment] 2021-09-24 12:49
After some investigation with the help of @jorblancoa and @alkino, we have concluded that this is **not** an issue specifically in MorphIO but any library that uses MPI in general, including `mpi4py`:

```
import os
from mpi4py import MPI 
os.execve('/bin/ls', ('-al',))
```

The issue here is that the example code is replacing the original process, which leads to undefined behaviour in MPI. In fact, the MPI standard reflects that forking and related support is undefined and depends on MPI implementations.

In the previous example, if you comment the line `from mpi4py import MPI`, you can run the script as many times as you want. After you uncomment the line and try again, the issue appears and it will continue failing unless you `kill -9` the conflictive Python process that is running in the background holding the CPU and other resources.

**My suggestion is to close this issue here and to create a separate Jira ticket in our backlog to investigate this matter in the future.** For now, we can safely assume that MorphIO is not the problem.

**Closed by sergiorg-hpc** 2021-09-24 12:49 UTC

**Comment by alkino** [comment] 2021-09-24 12:57
The problem seems to be that a python process is keeping an hand on the WORLD MPI communication channel, and so from there no one can talk on MPI.

Just probabilities.

**Comment by mgeplf** [comment] 2021-09-27 07:42
Great, thanks for looking into it.
